# permissions for end users to edit resourcemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcemonitor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: resourcemonitor
    app.kubernetes.io/part-of: resourcemonitor
    app.kubernetes.io/managed-by: kustomize
  name: resourcemonitor-editor-role
rules:
- apiGroups:
  - monitor.example.com
  resources:
  - resourcemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.example.com
  resources:
  - resourcemonitors/status
  verbs:
  - get
